export const PROTEIN_ALIAS_GROUPS = [
  ['hnRNP A0', 'A0', 'HNRPA0', 'ROA0'],
  ['hnRNP A1', 'A1', 'HNRPA1', 'HNRPA1L3', 'UP1', 'ROA1', 'hnRNP-A1', 'hnRNP A1B'],
  ['hnRNP A1L1', 'A1L1'],
  ['hnRNP A1L2', 'A1L2'],
  ['hnRNP A2B1', 'A2B1', 'HNRNPA2', 'HNRNPB1', 'HNRPA2', 'HNRPA2B1', 'HNRPB1', 'RNPA2', 'SNRPB1', 'ROA2', 'RA33'],
  ['hnRNP A3', 'A3', '2610510D13Rik', 'D10S102', 'FBRNP', 'HNRPA3', 'ROA3'],
  ['hnRNP AB', 'AB', 'ABBP1', 'HNRPAB'],
  ['hnRNP C', 'hnRNP C1', 'hnRNP C2', 'C(C1/C2)', 'HNRPC', 'SNRPC'],
  ['hnRNP CL1', 'CL1'],
  ['hnRNP D', 'AUF1', 'AUF1A', 'HNRPD', 'P37', 'hnRNPD0'],
  ['hnRNP DL', 'DL', 'HNRPDL', 'JKTBP', 'JKTBP2', 'laAUF1'],
  ['hnRNP E1', 'E1', 'PCBP1', 'alphaCP1', 'αCP1'],
  ['hnRNP E2', 'E2', 'PCBP2', 'alphaCP2', 'αCP2'],
  ['hnRNP E3', 'E3', 'PCBP3', 'alphaCP3', 'αCP3'],
  ['hnRNP E4', 'E4', 'PCBP4', 'alphaCP4', 'αCP4'],
  ['hnRNP F', 'HNRPF', 'OK/SW-cl.23', 'mcs94-1', 'nucleolin like protein'],
  ['hnRNP G', 'RBMX', 'HNRNPG', 'RNMX'],
  ['hnRNP GL1', 'GL1', 'RBMXL1', 'hnRNP G-like 1'],
  ['hnRNP GL2', 'GL2', 'RBMXL2', 'hnRNP G-like 2'],
  ['hnRNP H1', 'hnRNP H', 'H1(H)', 'HNRPH', 'HNRPH1', 'hnRNPH'],
  ["hnRNP H'", 'hnRNP H2', "H'(H2)", 'FTP3', "HNRPH'", 'HNRPH2', "hnRNPH'"],
  ['hnRNP H3', 'H3', '2H9', 'HNRPH3'],
  ['hnRNP I', 'PTBP1', 'PTB'],
  ['hnRNP K', 'CSBP', 'HNRPK', 'TUNP'],
  ['hnRNP L', 'HNRPL', 'hnRNP-L'],
  ['hnRNP LL', 'HNRPLL', 'SRRF'],
  ['hnRNP M', 'CEAR', 'HNRNPM4', 'HNRPM', 'HNRPM4', 'HTGR1', 'NAGR1'],
  ['hnRNP Q', 'SYNCRIP', 'NSAP1', 'HNRNPQ', 'GRY-RBP', 'PP68'],
  ['hnRNP R', 'HNRPR', 'hnRNP-R'],
  ['hnRNP U', 'HNRPU', 'SAF-A', 'U21.1'],
  ['hnRNP UL1', 'UL1', 'E1B-AP5', 'E1BAP5', 'HNRPUL1'],
  ['hnRNP UL2', 'UL2', 'HNRPUL2', 'SAF-A2'],
  ['RALY', 'HNRPCL2', 'P542'],
  ['SRSF1', 'SRSF 1', 'SRSF-1', 'ASF', 'ASF/SF2', 'SF2', 'SF2p33', 'SRp30a', 'MGC5228', 'SFRS1'],
  ['SRSF2', 'SRSF 2', 'SRSF-2', 'SC35', 'SC-35', 'PR264', 'SFRS2', 'SRp30b'],
  ['SRSF3', 'SRSF 3', 'SRSF-3', 'SRp20', 'SFRS3', 'SRP20'],
  ['SRSF4', 'SRSF 4', 'SRSF-4', 'SFRS4', 'SRP75'],
  ['SRSF5', 'SRSF 5', 'SRSF-5', 'HRS', 'SFRS5', 'SRp40'],
  ['SRSF6', 'SRSF 6', 'SRSF-6', 'SFRS6', 'SRp55'],
  ['SRSF7', 'SRSF 7', 'SRSF-7', '9G8', 'SFRS7', 'SRp20'],
  ['SRSF8', 'SRSF 8', 'SRSF-8', 'SFRS2B', 'SRP46'],
  ['SRSF9', 'SRSF 9', 'SRSF-9', 'SRp30c', 'SFRS9'],
  ['SRSF10', 'SRSF 10', 'SRSF-10', 'SRp38', 'FUSIP1', 'FUSIP2', 'SFRS13A', 'TASR'],
  ['SRSF11', 'SRSF 11', 'SRSF-11', 'SFRS11', 'p54'],
  ['SRSF12', 'SRSF 12', 'SRSF-12', 'SFRS13B', 'SFRS19', 'SRRP35', 'SRrp35'],
] as const;
